[build]
  # Next.js build command
  command = "next build"

[functions]
  # Set the timeout for your Node.js serverless function (your API route)
  timeout = 15
  # Use the faster bundler for functions
  node_bundler = "esbuild"

# Explicitly use the Netlify Next.js Build Plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"